import ControlBar from '#components/ControlBar/ControlBar'
import NavBar from '#components/NavBar/NavBar'
import Head from 'next/head'
import React from 'react'
import styles from '#styles/components/PageTemplate/PageTemplate.module.css'

interface PageTemplatePropsType {
  children: JSX.Element
  title: string
  controlBar?: boolean
  navBar?: boolean
}

const PageTemplate = ({ children, title, controlBar, navBar }: PageTemplatePropsType): JSX.Element => {
  const Content = (): JSX.Element => {
    if (controlBar != null) {
      return (
        <ControlBar>
          {children}
        </ControlBar>
      )
    }
    return (
      <>
      {children}
      </>
    )
  }

  return (
    <>
    <Head>
      <title>{'ERP-' + title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {navBar != null
      ? <NavBar>
          <div className={styles.pageContainer}>
            <Content />
          </div>
        </NavBar>
      : <div className={styles.pageContainer}>
          <Content />
        </div>}

    </>
  )
}

export default PageTemplate
